title: Michael Hanna
author: Michael Hanna
email: michaelwesley.hanna@studenti.unitn.it
logo: /assets/img/logo.jpg
remote-theme: pages-themes/minimal@v0.2.0
google_analytics: G-19NNF9EEH5

plugins:
- jekyll-remote-theme
